---
- name: Add vagrant user to docker group.
  user:
    name: vagrant
    groups: docker
    append: yes
  become: yes

- name: Install Pip.
  apt: name=python-pip state=installed
  become: yes

- name: Install Docker Python library.
  pip: name=docker-py state=present
  become: yes

- name: Build Dockers containers
  shell: docker-compose -f /vagrant/provisioning/docker/docker-compose.yml up -d {{item}}
  with_items: "{{docker_images}}"