---
- name: add repository java
  apt_repository:
    repo: 'ppa:openjdk-r/ppa'

- name: install java
  apt: name=openjdk-8-jdk state=present update_cache='yes'

- name: Add JAVA_HOME
  shell: echo 'JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64' >> /home/vagrant/.bashrc && echo 'export JAVA_HOME' >> /home/vagrant/.bashrc